routes/web.php
<?php

Auth::routes();

Route::get('/', 'MenuController@beranda');
Route::get('/2', 'MenuController@menu2');
Route::get('/3', 'MenuController@menu3');
Route::get('/4', 'MenuController@menu4');
Route::get('/5', 'MenuController@menu5');
Route::get('/6', 'MenuController@menu6');

Route::prefix('admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

    Route::resource('content', 'AdminController')->only('edit', 'update');

    Route::resource('menu1', 'Menu1Controller');
    Route::resource('menu1section1', 'Menu1Section1Controller');
    Route::resource('menu1section2', 'Menu1Section2Controller');
    Route::resource('menu1section3', 'Menu1Section3Controller');
});


Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

resources/views/admin/beranda/section1/create.blade.php
@extends('layouts.app', ['activePage' => 'beranda', 'titlePage' => __('Section 1')])

@section('content')

<style>
    html { overflow-y: scroll; }
</style>

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <form method="post" action="{{ route('menu1section1.store') }}" enctype="multipart/form-data" autocomplete="off" class="form-horizontal">
                    @csrf
                    @method('post')

                    <div class="card ">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title">{{ __('Tambah Data') }}</h4>
                            <p class="card-category"></p>
                        </div>
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-md-12 text-left">
                                    <a href="{{ route('menu1.index') }}" class="btn btn-sm btn-primary">{{ __('Kembali') }}</a>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 col-form-label">{{ __('Image') }}</label>
                                <div class="col-sm-5">
                                    <input type="file" name="image" id="foto" class="form-control">
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 col-form-label"></label>
                                <div class="col-sm-5">
                                    <img id="show" src="#" alt=" No Image" width="100%"/>
                                </div>
                            </div>

                            <div class="row">
                            <label class="col-sm-2 col-form-label">{{ __('Judul') }}</label>
                            <div class="col-sm-7">
                                <div class="form-group">
                                    <input class="form-control" name="title" type="text" placeholder="{{ __('Judul') }}"/>
                                </div>
                            </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 col-form-label">{{ __('Keterangan') }}</label>
                                <div class="col-sm-7">
                                    <div class="form-group">
                                        <input class="form-control" name="desc" type="text" placeholder="{{ __('Keterangan') }}"/>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer ml-auto mr-auto">
                            <button type="submit" class="btn btn-primary">{{ __('Simpan') }}</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
            $('#show').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
        }
    }

    $("#foto").change(function() {
        readURL(this);
    });
</script>
@endsection

resources/views/admin/beranda/section1/edit.blade.php
@extends('layouts.app', ['activePage' => 'beranda', 'titlePage' => __('Section 1')])

@section('content')

<style>
    html { overflow-y: scroll; }
</style>

<div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('menu1section1.update', $data) }}" enctype="multipart/form-data" autocomplete="off" class="form-horizontal">
            @csrf
            @method('put')

            @if (session('error'))
            <div class="row">
                <div class="col-sm-12">
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <i class="material-icons">close</i>
                        </button>
                        <span>{{ session('error') }}</span>
                    </div>
                </div>
            </div>
            @endif

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Edit Data') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('menu1.index') }}" class="btn btn-sm btn-primary">{{ __('Kembali') }}</a>
                  </div>
                </div>

                <div class="row">
                    <label class="col-sm-2 col-form-label">{{ __('Image') }}</label>
                    <div class="col-sm-5">
                        <input type="file" name="image" id="foto" class="form-control">
                    </div>
                </div>

                <div class="row">
                    <label class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-5">
                        <img id="show" src="{!! $data->image !!}" alt=" No Image" width="100%"/>
                    </div>
                </div>

                <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('Judul') }}</label>
                <div class="col-sm-7">
                    <div class="form-group">
                        <input class="form-control" value="{!! $data->title !!}" name="title" type="text" placeholder="{{ __('Judul') }}"/>
                    </div>
                </div>
                </div>

                <div class="row">
                    <label class="col-sm-2 col-form-label">{{ __('Keterangan') }}</label>
                    <div class="col-sm-7">
                        <div class="form-group">
                            <input class="form-control" value="{!! $data->desc !!}" name="desc" type="text" placeholder="{{ __('Keterangan') }}"/>
                        </div>
                    </div>
                </div>

              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
</div>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
            $('#show').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
        }
    }

    $("#foto").change(function() {
        readURL(this);
    });

</script>
@endsection